version: "3.7"

services:
  nextjs-app:
    image: seu-registro/nextjs-app:latest  # Substitua pelo nome da sua imagem
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - minha_rede
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=minha_rede"
        - "traefik.http.routers.nextjs-app.rule=Host(`seu-dominio.com`)"  # Substitua pelo seu domínio
        - "traefik.http.routers.nextjs-app.entrypoints=websecure"
        - "traefik.http.routers.nextjs-app.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.nextjs-app.loadbalancer.server.port=3000"
      replicas: 2  # Número de réplicas desejadas
      update_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: on-failure

networks:
  minha_rede:
    external: true
    name: minha_rede