version: "3.7"

services:
  wanderleyalino:
    build: .  # Adicionado para especificar que deve construir a partir do Dockerfile local
    networks:
      - minha_rede
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 512M
    labels:
      - traefik.enable=true
      - traefik.http.routers.wanderleyalino.rule=Host(`wanderleyalino.com`)
      - traefik.http.routers.wanderleyalino.entrypoints=websecure
      - traefik.http.routers.wanderleyalino.tls.certresolver=letsencryptresolver
      - traefik.http.routers.wanderleyalino.priority=1
      - traefik.http.services.wanderleyalino.loadbalancer.server.port=3000
      - traefik.http.services.wanderleyalino.loadbalancer.passHostHeader=true

networks:
  minha_rede:
    external: true